require("opts")
require("keymap")
require("autocmd")

require("deps")

vim.cmd.colorscheme("catppuccin-nvim")

require("plugins.cmp")
require("plugins.fzf-lua")
require("plugins.gitsigns")
require("plugins.harpoon")
require("plugins.mason")
require("plugins.lualine")
require("plugins.mini")
require("plugins.scrollEOF")
require("plugins.snacks")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.trouble")
require("plugins.easy-dotnet")
